site_name: Documentação

nav:
  - Seu Espaço UnB: index.md
  - Atas de Reunião:
    - Ata 1: atas-reuniao/ata-reuniao-17-04.md
    - Ata 2: atas-reuniao/ata-reuniao-27-04.md
    - Ata 3: atas-reuniao/ata-reuniao-29-04.md
    - Ata 4: atas-reuniao/ata-reuniao-04-05.md
  - Documentos:
    - Tabela - Integrantes do Grupo: visao-do-produto/tabela-integrantes-do-grupo.md
    - Tabela - Histórico de Revisões: visao-do-produto/tabela-historico-de-revisoes.md
    - Visão geral do produto: visao-do-produto/visao-geral-do-produto.md
    - Processo de desenvolvimento de software: visao-do-produto/processo-de-desenvolvimento-de-software.md
    - Declaração do escopo do projeto: visao-do-produto/declaracao-de-escopo-do-projeto.md
    - Métricas e Medições: visao-do-produto/metrica-e-medicoes.md

theme:
  name: material