site_name: Documentação

nav:
  - Instruções mkdocs: "index.md"
  - Atas de Reunião:
    - Ata 1: "atas-reuniao/ata-reuniao-17-04.md"
  - Documentos:
    - visao geral do produto: "visao-do-produto/visao-geral-do-produto.md"

theme:
  name: material